# Generated by Django 2.0 on 2018-01-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=None, to='studysystem.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_of_student',
            field=models.CharField(max_length=100),
        ),
    ]
