# Generated by Django 2.0 on 2018-01-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysystem', '0003_auto_20180113_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=None, to='course.Course'),
        ),
    ]
