# Generated by Django 2.0 on 2018-01-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('studysystem', '0004_auto_20180113_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(null=True, to='course.Course'),
        ),
    ]
